[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-Zshare-generics=off",
  "-Lnative=/home/edurf/.xwin/crt/lib/x86_64",
  "-Lnative=/home/edurf/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/edurf/.xwin/sdk/lib/ucrt/x86_64",
]
